# fly.toml app configuration file generated for morning-butterfly-7792 on 2023-06-29T16:48:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-butterfly-7792"
primary_region = "sea"

[env]
PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
